const K="alpha_v3_state";const now=()=>new Date().toISOString();const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random();const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));const esc=s=>String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
function fresh(){return{version:1,name:"ALPHA",cycle:0,learning:.5,exploration:.5,adaptation:.5,integration:1,memories:[],evolution:[],strategies:{exploration:.5,verification:.7,memoryThreshold:.45,reflection:.6,novelty:.55},selfModel:{currentFocus:"comprendre, apprendre et améliorer ses stratégies",confidence:.5,capabilities:["mémoire","apprentissage","dialogue","expérimentation","auto-observation","évolution"],limitations:["actif lorsque la page fonctionne","Internet dépend du navigateur","aucune conscience démontrée"]},conversation:[]}}
let S=(()=>{try{return JSON.parse(localStorage.getItem(K))||fresh()}catch{return fresh()}})();
function save(){S.updatedAt=now();localStorage.setItem(K,JSON.stringify(S))}
function addMemory(content,source="human",confidence=.7){S.memories.push({id:uid(),content,source,confidence,at:now()});if(S.memories.length>5000)S.memories.shift()}
function words(s){return new Set((s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").match(/[a-z0-9]{3,}/g)||[]))}
function recall(q){let qset=words(q);return S.memories.map(m=>{let w=words(m.content),n=0;for(let x of qset)if(w.has(x))n++;return{m,score:n+.1*m.confidence}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,6).map(x=>x.m)}
function answer(q){let m=recall(q),l=q.toLowerCase(),r;if(/qui es.?tu|qui es tu|ton etat|ton état|comment vas/.test(l))r=`Je suis ${S.name}. Mon cycle est ${S.cycle}. Je peux mémoriser, apprendre à partir des informations reçues, expérimenter et faire évoluer certaines stratégies internes.`;else if(m.length)r="J'ai retrouvé dans ma mémoire : "+m.map(x=>x.content).join(" | ");else r="Je n'ai pas encore de souvenir pertinent pour cette question. Je peux l'enregistrer comme élément à explorer.";addMemory("Question : "+q,"human",1);addMemory("Réponse : "+r,"alpha",.65);S.conversation.push({r:"human",t:q},{r:"alpha",t:r});S.conversation=S.conversation.slice(-80);S.cycle++;S.learning=clamp(S.learning+.002);save();render()}
function learn(t,source="human"){if(!t.trim())return;addMemory(t.slice(0,5000),source,.65);S.learning=clamp(S.learning+.01);S.cycle++;save();render()}
function score(){return +(S.learning*.3+S.adaptation*.3+S.integration*.2+S.exploration*.2).toFixed(4)}
function evolve(){let before={...S.strategies},k=Object.keys(before)[Math.floor(Math.random()*5)],d=[-.05,-.03,.03,.05][Math.floor(Math.random()*4)],after={...before,[k]:clamp(before[k]+d,.05,1)},sb=score();S.strategies=after;S.adaptation=clamp(S.adaptation+Math.abs(d)*.25);let sa=score();S.evolution.push({at:now(),reason:`Ajustement de ${k} (${d>0?"+":""}${d.toFixed(2)})`,before,after,scoreBefore:sb,scoreAfter:sa});S.cycle++;save();render();return S.evolution.at(-1)}
async function research(url){try{let u=new URL(url);if(!/^https?:$/.test(u.protocol))throw Error("URL HTTP/HTTPS uniquement");let r=await fetch(u.href),t=(await r.text()).replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim().slice(0,12000);learn(t,"internet");return t.slice(0,2500)}catch(e){return"Lecture impossible depuis ce navigateur : "+e.message+" (de nombreux sites bloquent les requêtes CORS)."}}
function render(){cycle.textContent=S.cycle;memoryCount.textContent=S.memories.length;knowledgeCount.textContent=S.memories.filter(x=>x.source==="internet"||x.source==="human").length;evolutionCount.textContent=S.evolution.length;stateLine.textContent=`Actif · apprentissage ${(S.learning*100).toFixed(0)}% · adaptation ${(S.adaptation*100).toFixed(0)}%`;focus.textContent=S.selfModel.currentFocus;selfModel.textContent=JSON.stringify({...S.selfModel,strategies:S.strategies},null,2);memory.innerHTML=S.memories.slice(-30).reverse().map(m=>`<div class="memoryItem"><b>[${esc(m.source)}]</b> ${esc(m.content)}<small>${new Date(m.at).toLocaleString("fr-FR")}</small></div>`).join("");journal.innerHTML=S.evolution.slice(-20).reverse().map(e=>`<div class="memoryItem"><b>${esc(e.reason)}</b><small>${new Date(e.at).toLocaleString("fr-FR")} · ${e.scoreBefore} → ${e.scoreAfter}</small></div>`).join("");chat.innerHTML=S.conversation.slice(-30).map(m=>`<div class="msg ${m.r==="alpha"?"alpha":""}"><b>${m.r==="alpha"?"ALPHA":"TOI"}</b><br>${esc(m.t)}</div>`).join("");status.textContent="● MÉMOIRE ACTIVE"}
send.onclick=()=>{let q=question.value.trim();if(q){answer(q);question.value=""}};question.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send.click()}};learn.onclick=()=>{let t=learnText.value.trim();if(t){learn(t);learnText.value=""}};evolve.onclick=()=>evolutionResult.textContent=JSON.stringify(evolve(),null,2);research.onclick=async()=>researchResult.textContent=await research(url.value.trim());exportState.onclick=()=>{let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:"application/json"}));a.download="alpha-memory.json";a.click()};importState.onchange=e=>{let f=e.target.files[0],r=new FileReader;r.onload=()=>{try{S=JSON.parse(r.result);save();render()}catch{alert("Mémoire invalide")}};r.readAsText(f)};render();